### ISSUE TITLE
Introduce support for BitBucket in Presidium Core

### ISSUE THREAD

**Issue by VirtualTraveler** [SPANDigital/presidium#141]
This should be an easy port since github and bitbucket are so similar

**Comment by ruaanvds** [comment]
Items that need to be addressed in order to facilitate this change: 

- Author links in front-matter
- Push a rendered site to BitBucket Cloud (like in gh-pages). See [this link](https://confluence.atlassian.com/bitbucket/publishing-a-website-on-bitbucket-cloud-221449776.html) for more info. 
- Update Presidium docs to make references to Github/version control generic.

**Comment by pacomendes** [comment]
Updated documentation with Bitbucket support:
http://presidium.spandigital.net/reference/front-matter/#authors
http://presidium.spandigital.net/getting-started/#publish-your-site
http://presidium.spandigital.net/recipes/hosting/#bitbucket
