### ISSUE TITLE
As a reader I would like to hide and expand the sidebar menu

### ISSUE THREAD

**Issue by MaddyCrews** [SPANDigital/presidium#22]

**Comment by MaddyCrews** [comment]
Provide the ability to hide and expand the sidebar menu when in full screen mode

**Comment by VirtualTraveler** [comment]
I'm not sure this is very high priority. The left menu provides the context for the article. Hiding the left menu removes tat context. Also, because the site is reactive, narrowing the browser window removes the left nav anyway. If you want to remove the left nav just shrink the width of the browser!

**Comment by ruaanvds** [comment]
Closing this for now. A tech spike was done to see how feasible this is. Given that Presidium JS initializes **after** page load, this was producing  FOUC (flash-of-unstyled-content).
